-- SCRIPT DO BANCO DE DADOS DE NOSSO PROJETINHO


-- TABELA "CURSO":
CREATE TABLE tb_curso(
    id_curso INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1 INCREMENT BY 1),
    nome_curso VARCHAR(90) NOT NULL,
    tipo_curso VARCHAR(50) NOT NULL
)

-- TABELA "ALUNO":
--FAREMOS NA PRÓXIMA AULA (PARAMOS AQUI)